name: Prepare runner for Ansible

on:
  workflow_dispatch:

jobs:
  prepare-runner:
    name: "Prepare runner with pip and Ansible"
    runs-on: self-hosted

    steps:
      - name: Ensure pip is installed
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py --user --break-system-packages

      - name: Add pip user bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Ansible
        run: pip3 install --user ansible

      - name: Check ansible version
        run: ansible --version
